feat: adding parameter preview to pass to api
chaordic/engage-onsite-sdk-js pull request #9
Opened 2021-03-05 13:18 UTC by andersonrostirolla

### Problema/Motivação
Explicado no PR: https://github.com/chaordic/onsite-dashboard/pull/18.

### O que foi feito
Adicionado o preview como um parametro para ser repassado para a api.

### Como testar

### Links úteis

* **Task no Jira:** [[onsite-dashboard] Pre-visualização do tema](https://jira.linx.com.br/browse/DIONS-270)

2021-03-08 14:41 UTC, CrashToDesktop requested changes

2021-03-08 14:41 UTC, CrashToDesktop commented on src/config/environment/development.json
> +}
Adicionar uma linha no final do arquivo, vale para os três arquivos de config.

2021-03-08 14:41 UTC, CrashToDesktop commented on src/facades/pages.js
> +    const urlGet = `${baseUrl}/pages/recommendations`;
O nome dessa variável poderia ser getPath ou getUrl.

2021-03-08 20:00 UTC, CrashToDesktop requested changes

2021-03-08 21:01 UTC, CrashToDesktop commented on src/config/environment/development.json
> +{
Uma coisa que eu ia sugerir sobre esses arquivos, é que poderiamos ter um arquivo "common", pra colocar algumas partes que se repetem nos três arquivos. Eu notei que você exporta os três arquivos durante o build então seria apenas uma questão de exportar um merge do env + common.

2021-03-11 16:12 UTC, CrashToDesktop requested changes

2021-03-11 16:12 UTC, CrashToDesktop commented on src/config/index.js
> +// Merge common configs to thrid environments.
three

2021-03-11 16:12 UTC, CrashToDesktop commented on src/config/index.js
> +Object.assign(development, common);
Como fica a precedência desse cara aqui? Se precisarmos modificar alguma propriedade no env que já exista no common acho que não vai funcionar.

2021-03-30 13:06 UTC, andersonrostirolla commented on src/config/index.js
> +Object.assign(development, common);
como assim?

2021-03-30 13:08 UTC, andersonrostirolla commented on src/config/index.js
> +Object.assign(development, common);
ah, vc diz sobrescrever algo do common no env especifico?

2021-03-30 13:12 UTC, andersonrostirolla commented on src/config/index.js
> +Object.assign(development, common);
Pelos testes que fiz aqui, se inverter a ordem do Object.assign eu automaticamente tenho o arquivo common, porém se tiver algo no ambiente espeficio que sobrescreva algo do common esse vira o novo arquivo. Só que pra fazer isso, vou precisar separar isso em outras variaveis, pois ele salva a info no primeiro do Object.assign, ou seja, salvaria no common e nao no ambiente solicitado

2021-03-30 17:58 UTC, CrashToDesktop approved these changes
LGTM

2021-03-30 20:26 UTC, IvaProtasio approved these changes
LGTM

2021-04-13 16:36 UTC, merged